#!/bin/bash

PS3="Хотите установить python?"

select variants in Да Нет
do
      case $variants in
      Да) echo "Вы выбрали установить python";;
     Нет) echo "Все равно установим";;
       *) echo "Все равно установим";;
      esac
done
